### ISSUE TITLE
Web sockets unable to connect in Safari using self-signed HTTPS

### ISSUE THREAD

**Issue by acallaghan** [reddit/reddit-plugin-liveupdate#100]
Hi there,

I've just installed reddit in a VM, using the local alias address https://reddit.local which is translated to the local IP address in my /etc/hosts file.

When I try and use liveupdate on the 'show' page, i.e. https://reddit.local/live/uarm25feeoj5 - Safari (8.0.2) doesn't ever connect, but Chrome does. In Safari's JS console output, it says the following:

```
[Debug] websocket: connecting (websocket.js, line 22)
[Error] WebSocket network error: OSStatus Error -9807: Invalid certificate chain  (uarm25feeoj5, line 0)
[Debug] websocket: connection lost, reconnecting in 511631ms (websocket.js, line 76)
[Debug] (can't connect? Make sure you've allowed https access in your browser.) (websocket.js, line 77)
```

Any ideas? Perhaps Safari is more strict with self-signed certs with websockets?

**Comment by spladug** [comment]
Very odd.  In the default install, the websocket stuff runs through the same stunnel with same configuration as the non-websocket stuff. It does seem rather odd that safari would be OK with one but not the other.

A few things turned up when googling that make it sound like a somewhat common problem: http://stackoverflow.com/questions/4014055/how-to-debug-safari-silently-failing-to-connect-to-a-secure-websocket and https://github.com/mrjoes/tornadio2/issues/59

If any of those tweaks suggested in those threads work for you, please do let me know so we see about mainlining them.

**Comment by spladug** [comment]
I'm going to close this out as it doesn't seem anything's come up in the past couple of years. Please reopen if you have more issues.
