### ISSUE TITLE
YouTube embeds not fullscreenable.

### ISSUE THREAD

**Issue by simontoft** [reddit/reddit-plugin-liveupdate#116]
YouTube embeds in live threads are not showing the fullscreen button. I tried locating where the issue occurs, but the embeds seem to be 3 nested iframes (Redditmedia -> Embedly -> Youtube) which made debugging hard.

**Comment by spladug** [comment]
Fixed in 62f9a1c47d33a87eb92696cb0687f266a8f5a5ff
