### ISSUE TITLE
Enhancement: On the mobile version of the website, allow users to enable popup notifications

### ISSUE THREAD

**Issue by m-p-3** [reddit/reddit-plugin-liveupdate#121]
# Current situation

Right now, it is only possible to activate the _popup notifications_ feature while browsing Reddit in desktop mode on a live thread.

Using the _Request desktop site_ in Google Chrome for Android has no effect on the UI, and the website remains with its mobile interface.
# Requested change

Since it is possible for websites to send push notifications to web browsers such as Google Chrome or Mozilla Firefox on desktop as well as on mobile, it would be useful to have the ability to enable such popups on a mobile.

For example, Facebook allow their users to get push notifications through the web browser. You can test the feature by enabling push notification [here](https://m.facebook.com/settings/notifications/push/) in your Facebook account on a supported web browser.
# Benefits

This would allow mobile users to get notified directly by the web browser, no matter what they're doing and stay up to date.
It would also grant smartwatch users to stay up to date on a live thread directly on their watch without holding their devices.

**Comment by 13steinj** [comment]
Pop up notifications? That sounds like @honestbleeps 's RES, not native reddit.

**Comment by spladug** [comment]
Live supports popups via the standard [Web Notifications](http://www.w3.org/TR/2015/REC-notifications-20151022/) spec.  The checkbox appears in the UI only if your browser supports it.  I believe mobile firefox does indeed support it, I'm not sure why mobile chrome does not.

**Comment by spladug** [comment]
I'm going to close this out as it should automatically be there if your browser supports the feature via the standard API. Please let me know if there's something else to consider.
