### ISSUE TITLE
Allow reporters to hide discussion links in sidebar.

### ISSUE THREAD

**Issue by spladug** [reddit/reddit-plugin-liveupdate#14]

**Comment by kblanks** [comment]
Almost a 3 year bump, woah.

![slack logs with reddit admins](https://i.imgur.com/k3cijBA.png)

I can look into creating a PR for this if it would be useful.

**Comment by legurnster** [comment]
@kblanks I would.

**Comment by 13steinj** [comment]
@kblanks yes please (and hopefully, let us remove individual links). If you need some help / don't feel up to it feel free to pm me (same username on reddit) / I'd love to look into this myself as well

**Comment by umbrae** [comment]
@kblanks If you're interested in taking a crack at it I would be happy to code review it for you!

**Comment by gxrney** [comment]
This is something that me and my team (volunteer Reddit Live Team) have had to call in Reddit engineers for a number of times and I hate hassling them while they're busy during major events such as conventions and disasters.

It'd be awesome to see us able to self-service this, if you can call it as such.

**Comment by kblanks** [comment]
I'm looking into creating a PR for this — just familiarising myself with
the Reddit codebase.

**Comment by gxrney** [comment]
Awesome! Thanks @kblanks.

**Comment by HaydenSD** [comment]
@kailan created a fork [here](https://github.com/VolunteerLiveTeam/reddit-plugin-liveupdate).

**Comment by spladug** [comment]
This was fixed in 79128070813001970c7c7e1ceaa6e730dcf291e3.
