### ISSUE TITLE
Embedly Scraper class name should be updated to be accordance with the r2 lib

### ISSUE THREAD

**Issue by wanliqun** [reddit/reddit-plugin-liveupdate#155]
line 16 from reddit-plugin-liveupdate/reddit_liveupdate/media_embeds.py:
from r2.lib.media import MediaEmbed, Scraper, get_media_embed, _OEmbedScraper

however from reddit/r2/r2/lib/media.py line 777 the class name has been changed to _EmbedlyScraper.

Without the update, this will incurs the "ImportError: cannot import name _OEmbedScraper"

**Comment by spladug** [comment]
Things look in-sync on my end, this may be an unfortunate issue with the archiving of reddit/reddit. I'm going to close this out.
