### ISSUE TITLE
Some livemanage related endpoints return 403

### ISSUE THREAD

**Issue by markspolakovs** [reddit/reddit-plugin-liveupdate#158]
See the /r/bugs thread at https://www.reddit.com/r/bugs/comments/6dl4ep/reddit_live_some_livemanage_related_endpoints/

**Comment by nmtake** [comment]
Plese also see [this report](https://www.reddit.com/r/bugs/comments/6i9lvv/oauth2_scope_is_missing_livemanage/) at /r/bugs. If a user asks 
`livemanage` scope (and `read` pemrission for some API wrapper users) explicitly
with OAuth2 code flow, `/api/live/:thread/edit` and `/api/live/:thread/invite_contributor` returns 200.

**Comment by markspolakovs** [comment]
[Reported as fixed](https://www.reddit.com/r/bugs/comments/6dl4ep/reddit_live_some_livemanage_related_endpoints/djwm3x8/)
