### ISSUE TITLE
Add listing for all created/invited live threads

### ISSUE THREAD

**Issue by rctgamer3** [reddit/reddit-plugin-liveupdate#91]
As an updater for TwitchPlaysPokémon, i've been an updater on 8 different live updaters, if not more.
It would be useful if I could check somewhere what live updaters I've created and/or have been invited to. Unless you know the exact URL of the Live Updater (or it has a custom slug like /splatest) they're unfindable.

**Comment by 13steinj** [comment]
@spladug While the /live/mine would be nice; looking at other users' would be nice too, just like /u/me has the corresponding /u/username

**Comment by rctgamer3** [comment]
This would still be a /nice to have/ feature.
